config/routes.rb
Rails.application.routes.draw do
  resources :chats do
    collection do
      get "socket"
      get "load"
    end
  end

  resources :conversations
  resources :forums, only: [:index]
  resources :submissions, path: "threads" do
    resources :posts, only: [:create]

    member do
      get "unread"
    end
  end

  resources :posts do
    member do
      post "thanks"
      get "redirect"
    end
  end

  devise_for :users,  path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" },
                      controllers: { sessions: "sessions" }

  authenticated :user do
    root to: "users#root", as: :authenticated_root
  end

  unauthenticated do
    root to: "forums#index"
  end

  get "about" => "pages#about"
  get "rules" => "pages#rules"
  get "members" => "users#index", as: :members

  resources :users do
    member do
      delete "spammer"
    end
  end

  get "profile" => "profile#edit"
  get "profile/avatar" => "profile#avatar"
  get "profile/settings" => "profile#settings"
  get "profile/signature" => "profile#signature"

  get "forums/:forum_id" => "submissions#index", as: :forum

  get "search" => "search#index"
  post "search" => "search#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %i[admin banned]

  extend FriendlyId
  friendly_id :username, use: :slugged

  acts_as_paranoid

  has_many :submissions, foreign_key: "author_id"
  has_many :posts, foreign_key: "author_id"
  has_many :thanks
  has_many :views, dependent: :destroy

  has_many :conversations, through: :conversations_users
  has_many :conversations_users

  before_validation :https_avatar_url
  validates :avatar_url, format: { with: /\Ahttps\:\/\/i\.imgur\.com\/(\w+)\.(png|jpe?g)\Z/, allow_nil: true, unless: Proc.new { |user| user.avatar_url == "pixel-admin/avatar.png" } }

  def avatar_url
    read_attribute(:avatar_url) || "pixel-admin/avatar.png"
  end

  def to_s
    username
  end

  def https_avatar_url
    url = avatar_url.to_s
    url.sub!("http:", "https:")
    url = nil if url.blank?

    self.avatar_url = url
  end

  def admin?
    role == "admin"
  end

  def top_posts
    Post.unscoped.
      where(author: self).
      where("deleted_at IS NULL").
      where("thanks_count IS NOT NULL AND thanks_count > 0").
      order("thanks_count DESC").
      limit(10)
  end

  def spammer!
    submissions.all.each do |s|
      s.posts.destroy
      s = Submission.unscoped.find(s.id)
      s.destroy
    end

    self.destroy
  end

  # This method returns data for the "Loved By" and "Favorite Posters" tables
  # in the user profile.
  def most_thanks(mine)
    mine = (mine == :loved_by)

    if mine
      sql = <<EOS
        SELECT  user_id,
                COUNT(user_id) AS thanks_count
        FROM    thanks
        WHERE   thanks.post_id IN
                  (SELECT id FROM posts WHERE posts.author_id = #{id})
                  AND
                  thanks.deleted_at IS NULL
        GROUP BY user_id
        ORDER BY thanks_count DESC
        LIMIT 10
EOS
    else
      sql = <<EOS
        SELECT      posts.author_id AS user_id,
                    COUNT(posts.author_id) AS thanks_count
        FROM        thanks
        INNER JOIN  posts
        ON          posts.id = thanks.post_id
        WHERE       user_id = #{id}
        GROUP BY    posts.author_id
        ORDER BY    thanks_count DESC
        LIMIT 10
EOS
    end

    chart = ActiveRecord::Base.connection.execute(sql).to_a
    
    User.where("id IN (?)", chart.map { |res| res["user_id"] }).map do |user|
      [user, chart.find { |res| res["user_id"].to_i == user.id }["thanks_count"].to_i ]
    end.sort_by { |lover| lover[1] }.reverse
  end

  def unread_messages_count
    join = <<EOS
    INNER JOIN
      (
        SELECT    conversation_id,
                  MAX(created_at)
        AS        last_chat_at
        FROM      chats
        GROUP BY  conversation_id
      )
    AS chats
    ON chats.conversation_id = conversations_users.conversation_id
EOS

    ConversationsUser.joins(join).
      where(user_id: id).
      where("conversations_users.read_at IS NULL OR conversations_users.read_at < chats.last_chat_at").
      count
  end

  def self.lookup(username)
    User.where("lower(username) = ?", username.to_s.strip.downcase).first
  end

  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :gender, numericality: { less_than_or_equal_to: 2, greater_than_or_equal_to: 0 }

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order("created_at ASC")
  end

  def spammer
    @user = User.friendly.find(params[:id])
    @user.spammer!

    redirect_to root_path, notice: "User deleted."
  end

  def update
    if current_user.update_attributes(update_user_params)
      redirect_to :back, notice: "Updated successfully!"
    else
      redirect_to :back, alert: "There was a problem with your submission."
    end
  end

  def root
    if user_signed_in? && current_user.whats_new_default?
      redirect_to submissions_path
    else
      redirect_to forums_path
    end
  end

  def show
    @user = User.friendly.find(params[:id])
    @user.increment!(:profile_views)
  end

  private
  def update_user_params
    params.require(:user).permit(:avatar_url, :title, :country, :time_zone, :location, :signature, :password, :password_confirmation, :whats_new_default)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
.page-header
  %h1 Members

.row
  .col-md-10.col-md-offset-1
    %table{class: "table table-striped"}
      %thead
        %tr
          %th Username
          %th Joined On
          %th Posts

      %tbody
        - @users.each do |user|
          %tr
            %td= link_to user, user
            %td= l user.created_at
            %td= user.posts.count

app/views/users/show.html.haml
- content_for(:body_class, "page-profile")

.profile-full-name
  %span.text-semibold>= @user
  's profile
.profile-row
  .left-col
    .profile-block
      .panel.profile-photo
        = image_tag @user.avatar_url
    .panel.panel-transparent
      .panel-heading
        %span.panel-title Title
      .panel-body
        = @user.title
    .panel.panel-transparent
      .panel-heading
        %span.panel-title Statistics
      .list-group
        .list-group-item
          %strong= @user.profile_views
          Profile Views
        .list-group-item
          %strong= @user.posts.count
          Posts
        .list-group-item
          %strong= Thank.thank_stats_for(@user)[0]
          Thanks
    - if current_user.admin?
      .panel.panel-transparent
        .panel-heading
          %span.panel-title Admin
        .list-group
          .list-group-item
            = link_to "Spammer!", spammer_user_path(@user), method: :delete, confirm: "Are you sure you want to delete this user and all its posts?"
  .right-col
    %hr.profile-content-hr.no-grid-gutter-h/
    .profile-content
      %ul#profile-tabs.nav.nav-tabs
        %li.active
          %a{"data-toggle" => "tab", :href => "#profile-tabs-top-posts"} Top Posts
        %li
          %a{"data-toggle" => "tab", :href => "#profile-tabs-favorite-posters"} Favorite Posters
        %li
          %a{"data-toggle" => "tab", :href => "#profile-tabs-loved-by"} Loved By
      .tab-content.tab-content-bordered.panel-padding
        #profile-tabs-top-posts.widget-article-comments.tab-pane.panel.no-padding.no-border.active
          %table.table
            %thead
              %tr
                %th Post
                %th Thanks
            %tbody
              - @user.top_posts.each do |post|
                %tr
                  %td= link_to truncate_and_remove_quotes(post.body), submission_path(post.submission, page: post.page, anchor: "post-#{post.id}")
                  %td= post.thanks_count

        #profile-tabs-favorite-posters.widget-followers.tab-pane.panel.no-padding.no-border
          %table.table
            %thead
              %tr
                %th User
                %th= "Times Thanked by #{@user}"
            %tbody
              - @user.most_thanks(:favorite_users).each do |favorite|
                %tr
                  %td
                    = image_tag(favorite[0].avatar_url, class: "avatar", height: 40, width: 40)
                    = link_to favorite[0], favorite[0]
                  %td
                    = favorite[1]

        #profile-tabs-loved-by.widget-followers.tab-pane.panel.no-padding.no-border
          %table.table
            %thead
              %tr
                %th User
                %th= "Thanks Given to #{@user}"
            %tbody
              - @user.most_thanks(:loved_by).each do |lover|
                %tr
                  %td
                    = image_tag(lover[0].avatar_url, class: "avatar", height: 40, width: 40)
                    = link_to lover[0], lover[0]
                  %td
                    = lover[1]