config/routes.rb
Rails.application.routes.draw do
  resources :chats do
    collection do
      get "socket"
      get "load"
    end
  end

  resources :conversations
  resources :forums, only: [:index]
  resources :submissions, path: "threads" do
    resources :posts, only: [:create]

    member do
      get "unread"
    end
  end

  resources :posts do
    member do
      post "thanks"
      get "redirect"
    end
  end

  devise_for :users,  path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" },
                      controllers: { sessions: "sessions" }

  authenticated :user do
    root to: "users#root", as: :authenticated_root
  end

  unauthenticated do
    root to: "forums#index"
  end

  get "about" => "pages#about"
  get "rules" => "pages#rules"
  get "members" => "users#index", as: :members

  resources :users do
    member do
      delete "spammer"
    end
  end

  get "profile" => "profile#edit"
  get "profile/avatar" => "profile#avatar"
  get "profile/settings" => "profile#settings"
  get "profile/signature" => "profile#signature"

  get "forums/:forum_id" => "submissions#index", as: :forum

  get "search" => "search#index"
  post "search" => "search#index"
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_paranoid

  scope :not_secret, -> { where("secret IS NOT true") }

  belongs_to :forum
  belongs_to :author, class_name: "User"
  has_many :posts, -> { order "created_at ASC" }, dependent: :destroy
  has_many :views, dependent: :destroy

  validates :title, presence: true
  validates :author_id, presence: true

  def to_s
    title
  end

  def has_posts_by?(user)
    return false unless user
    posts.where(author_id: user.id).exists?
  end

  def first_unread_post(user)
    return posts.first unless user

    view = View.find_by(user_id: user.id, submission_id: id)
    post = nil

    if view
      # First post created AFTER the last view.
      post = posts.where("created_at > ?", view.viewed_at).first
    else
      # If we haven't viewed the thread before, first post.
      post = posts.first
    end

    # If nothing matches, send them to the last post.
    post || posts.last
  end

  def viewed!(user)
    return false unless user

    view = View.find_or_create_by(user_id: user.id, submission_id: id)
    view.update(viewed_at: Time.now)
  end

  def viewed_by?(user, views = nil)
    return true if updated_at < Time.now - 1.week
    return false unless user
    return false unless views

    view = views.find { |v| v.submission_id == id }
    view && view.viewed_at >= updated_at
  end

  def alt_text
    posts.first.body.gsub(/\s+/, " ")[0..255]
  rescue
    ""
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :unread, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :unread]
  before_action :set_page, only: [:index, :show]
  before_action :set_forum, only: [:index]

  def index
    @submissions = Submission.includes(posts: [:author]).includes(:forum).order("updated_at DESC")
    @submissions = @submissions.where(forum_id: @forum.id) if @forum

    if user_signed_in?
      @views = current_user.views.where("submission_id IN (?)", @submissions.map(&:id))
    else
      @submissions = @submissions.not_secret
    end

    @submissions = @submissions.page(@page)
    @posted_submission_ids = Post.select("submission_id").where(author_id: current_user.id).where("submission_id IN (?)", @submissions.map(&:id)).map(&:submission_id) if user_signed_in?
  end

  def show
    @posts = @submission.posts.page(@page)
    @submission.viewed!(current_user)
  end

  def unread
    post = @submission.first_unread_post(current_user)

    redirect_to submission_path(@submission, page: post.page, anchor: "post-#{post.id}")
  end

  def edit
  end

  def create
    @submission = current_user.submissions.new(submission_params)
    @post = Post.new(post_params)

    if @submission.save
      @post.submission = @submission
      @post.author = current_user
      @post.save

      redirect_to @submission, notice: "Submission was successfully created."
    else
      redirect_to submissions_path, alert: "Error saving thread."
    end
  end

  def update
    if @submission.update(submission_params)
      redirect_to @submission, notice: "Submission was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @submission.destroy
    redirect_to submissions_path, notice: "Submission was successfully destroyed."
  end

  private
  def set_submission
    @submission = Submission.friendly.find(params[:id])

    if !user_signed_in? && @submission.secret?
      redirect_to root_path
    end
  end

  def submission_params
    params.require(:submission).permit(:title, :forum_id, posts_attributes: [:body])
  end

  def post_params
    params.require(:post).permit(:body)
  end

  def set_page
    @page = params[:page].to_i || 1
  end

  def set_forum
    @forum = Forum.friendly.find(params[:forum_id]) if params[:forum_id].present?
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_index.html.haml
.row
  %table{class: "table table-striped"}
    %thead
      %tr
        %th Title
        %th Forum
        %th Replies
        %th Last Post By

    %tbody
      - submissions.each do |submission|
        %tr
          %td
            - if @posted_submission_ids && @posted_submission_ids.include?(submission.id)
              %i.fa.fa-leaf{style: "color: green"}

            - if submission.viewed_by?(current_user, @views)
              = link_to submission, unread_submission_path(submission), title: submission.alt_text
            - else
              %strong
                = link_to submission, unread_submission_path(submission), title: submission.alt_text
            %br
            Started by
            = link_to(submission.posts.first.author, submission.posts.first.author) rescue ""
          %td= link_to submission.forum, submission.forum
          %td= submission.posts_count - 1
          %td
            = link_to(submission.posts.last.author, submission.posts.last.author) rescue ""
            %br
            = l(submission.posts.last.created_at) rescue ""

.row
  .pull-right{style: "margin-right: 12px"}
    %p
      = paginate submissions

app/views/submissions/_new.html.haml
#new-thread-modal.modal.fade{role: "dialog"}
  = form_for Submission.new, html: { id: "new-thread-form", class: "form-horizontal" } do |f|
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %h4.modal-title New Thread
        .modal-body
          .row.form-group
            = f.label :forum_id, class: "col-sm-2 control-label"
            .col-sm-10
              = f.select :forum_id, options_from_collection_for_select(Forum.all, :id, :title, @forum.try(:id) || Forum.default_forum_id), {}, { class: "form-control" }
          .row.form-group
            = f.label :title, class: "col-sm-2 control-label"
            .col-sm-10
              = f.text_field :title, class: "form-control"
          = fields_for Post.new do |post_field|
            .row.form-group
              = post_field.label :body, class: "col-sm-2 control-label"
              .col-sm-10
                = post_field.text_area :body, class: "form-control markdown", rows: 15
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
          %button.btn.btn-primary{type: "submit"} Create Thread

app/views/submissions/index.html.haml
.page-header
  %h1
    = @forum || "What's New"

.col-md-10.col-md-offset-1
  .row
    .pull-left
      - last_chat = Chat.global.last
      Last Chat by
      %strong
        = last_chat.user
      = "(#{time_ago_in_words last_chat.created_at} ago)"

    .pull-right
      - if user_signed_in?
        %button.btn.btn-flat.btn-labeled.btn-primary{data: { toggle: "modal", target: "#new-thread-modal" }}
          %span.btn-label.icon.fa.fa-plus
          New Thread
      - else
        %a.btn.btn-flat.btn-labeled.btn-primary{href: new_user_registration_path}
          %span.btn-label.icon.fa.fa-plus
          New Thread

  = render partial: "submissions/index", locals: { submissions: @submissions }

- if user_signed_in?
  = render partial: "submissions/new"

app/views/submissions/show.html.haml
.page-header
  %h1
    = @submission

.col-sm-10.col-sm-offset-1
  .posts-wrapper{style: "clear:both"}
    .pull-left
      %p
        Posted in:
        = link_to @submission.forum, @submission.forum

    .row
      .pull-right{style: "margin-right: 12px"}
        %p
          = paginate @posts

    - @posts.each do |post|
      = render post

    .row
      .pull-right{style: "margin-right: 12px"}
        = paginate @posts
        %br
        %br

  .message-details-reply
    - if user_signed_in?
      = form_for [@submission, @submission.posts.new], { remote: true, html: { id: "message-details-reply" } } do |f|
        = hidden_field_tag :last_post_id, @submission.posts.where("id IS NOT NULL").last.id
        = f.text_area :body, class: "form-control markdown", rows: 10
        .row{style: "margin-top: 10px; margin-right: 5px;"}
          %button.btn.btn-primary.pull-right Post to Thread
    - else
      %p Sign in to reply!