config/routes.rb
Rails.application.routes.draw do
  resources :chats do
    collection do
      get "socket"
      get "load"
    end
  end

  resources :conversations
  resources :forums, only: [:index]
  resources :submissions, path: "threads" do
    resources :posts, only: [:create]

    member do
      get "unread"
    end
  end

  resources :posts do
    member do
      post "thanks"
      get "redirect"
    end
  end

  devise_for :users,  path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" },
                      controllers: { sessions: "sessions" }

  authenticated :user do
    root to: "users#root", as: :authenticated_root
  end

  unauthenticated do
    root to: "forums#index"
  end

  get "about" => "pages#about"
  get "rules" => "pages#rules"
  get "members" => "users#index", as: :members

  resources :users do
    member do
      delete "spammer"
    end
  end

  get "profile" => "profile#edit"
  get "profile/avatar" => "profile#avatar"
  get "profile/settings" => "profile#settings"
  get "profile/signature" => "profile#signature"

  get "forums/:forum_id" => "submissions#index", as: :forum

  get "search" => "search#index"
  post "search" => "search#index"
end

app/views/layouts/application.html.haml
!!!
/[if IE 8] <html class="ie8">
/[if IE 9] <html class="ie9 gt-ie8">
/ [if gt IE 9]><!
%html.gt-ie8.gt-ie9.not-ie
  / <![endif]
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
    %title
      Relationship Forum
      |
      - if @submission.present?
        = @submission.title
      - elsif @forum.present?
        = @forum.title
      - else
        Online Love Discussion
    %meta{content: "width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0", name: "viewport"}
    %link{href: "//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin", rel: "stylesheet", type: "text/css"}
    %link{href: "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css", rel: "stylesheet"}
    %link{href: "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css", rel: "stylesheet"}
    %link{href: "/favicon.ico", rel: "shortcut icon"}
    %meta{name: "keywords", content: "relationship forum"}
    = meta_description

    = stylesheet_link_tag :application
    = javascript_include_tag :application

  %body{class: body_class}
    = yield(:menu)

    - if devise_controller?
      = yield
    - else
      #main-wrapper
        #main-navbar.navbar.navbar-inverse{role: "navigation"}
          .navbar-inner
            .navbar-header
              %a.navbar-brand{href: root_path}
                %img{alt: "Relationship Forum", src: asset_path("logo-small.png")}
              %button.navbar-toggle.collapsed{"data-target" => "#main-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
                %i.navbar-icon.fa.fa-bars
            #main-navbar-collapse.collapse.navbar-collapse.main-navbar-collapse
              %div
                %ul.nav.navbar-nav
                  %li
                    %a{href: submissions_path} What's New?
                  %li
                    %a{href: forums_path} Forums
                  %li
                    %a{href: chats_path} Chat
                .right.clearfix
                  %ul.nav.navbar-nav.pull-right.right-navbar-nav
                    - if user_signed_in?
                      %li.nav-icon-btn
                        %a{href: search_path}
                          %i.nav-icon.fa.fa-search
                      %li.nav-icon-btn.nav-icon-btn-success
                        %a{href: conversations_path}
                          - if total_unread_messages > 0
                            %span{class: "label"}
                              = total_unread_messages
                          %i.nav-icon.fa.fa-envelope
                      %li.dropdown
                        %a.dropdown-toggle.user-menu{"data-toggle" => "dropdown", :href => "#"}
                          = avatar
                          %span#user{data: { id: current_user.id }}
                            = current_user
                        %ul.dropdown-menu
                          %li
                            %a{href: profile_path}
                              %i.dropdown-icon.fa.fa-user
                              \&nbsp;&nbsp;Profile
                          %li
                            %a{href: profile_settings_path}
                              %i.dropdown-icon.fa.fa-cog
                              \&nbsp;&nbsp;Settings
                          %li.divider
                          %li
                            %a{href: destroy_user_session_path}
                              %i.dropdown-icon.fa.fa-power-off
                              \&nbsp;&nbsp;Log Out
                    - else
                      %li
                        = link_to "Register", new_user_registration_path
                      %li
                        = link_to "Login", new_user_session_path
        #content-wrapper
          .row
            - flash.each do |type, msg|
              .col-sm-12
                = content_tag :div, msg, class: "alert alert-#{type == "notice" ? "success" : "danger"}"

          = yield(:mailnav) if content_for?(:mailnav)
          = content_for?(:content) ? yield(:content) : yield


        #main-menu-bg

        - unless content_for?(:menu) || content_for?(:mailnav)
          %footer.col-md-10.col-md-offset-1
            .row{style: "text-align: center"}
              = link_to "About", "/about"
              &bull;
              = link_to "Members", members_path
              &bull;
              = link_to "Google+", "https://plus.google.com/+RelationshipforumOrg1", rel: "publisher"
              &bull;
              = link_to "Twitter", "https://twitter.com/relations_forum"
              &bull;
              = link_to "GitHub", "https://github.com/relationshipforum/blackbits"

    - if Rails.env == "production"
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-52684204-1', 'auto');
        ga('send', 'pageview');

app/views/layouts/conversations.html.haml
- content_for :body_class, "page-mail"

- content_for :mailnav do
  .mail-nav
    .compose-btn
      %button.btn.btn-primary.btn-labeled.btn-block#new-conversation
        %i.btn-label.fa.fa-pencil-square-o>
        New Conversation
    .navigation.open
      %ul.sections
        - @conversations.each do |conversation|
          %li{class: @conversation == conversation ? "active" : ""}
            %a{href: conversation_path(conversation)}
              %i.m-nav-icon.fa.fa-heart>
              = conversation_title(conversation)
              - if (unread_count = unread_messages(conversation)) > 0
                %span.label.pull-right
                  = unread_count

= render template: "layouts/application"

app/views/layouts/profile.html.haml
- content_for :menu do
  #main-menu{:role => "navigation"}
    #main-menu-inner
      #menu-content-demo.menu-content.top
        %div
          .text-bg
            %span.text-semibold= current_user
          = avatar
          .btn-group
            %a.btn.btn-xs.btn-primary.btn-outline.dark{href: conversations_path}
              %i.fa.fa-envelope
            %a.btn.btn-xs.btn-danger.btn-outline.dark{href: destroy_user_session_path}
              %i.fa.fa-power-off
          %a.close{href: root_path} &times;
      %ul.navigation
        %li{class: action_name == "edit" ? "active" : ""}
          %a{href: profile_path}
            %i.menu-icon.fa.fa-user
            %span.mm-text Profile
        %li{class: action_name == "avatar" ? "active" : ""}
          %a{href: profile_avatar_path}
            %i.menu-icon.fa.fa-camera
            %span.mm-text Avatar
        %li{class: action_name == "signature" ? "active" : ""}
          %a{href: profile_signature_path}
            %i.menu-icon.fa.fa-pencil
            %span.mm-text Signature
        %li{class: action_name == "settings" ? "active" : ""}
          %a{href: profile_settings_path}
            %i.menu-icon.fa.fa-cog
            %span.mm-text Settings

= render template: "layouts/application"